#!/bin/bash

echo "Executing migrations. This will remove all data on production dbs. Continue? [y,n]"
read -r input

if [ "$input" == "" ]; then
   exit 0
elif [[ "$input" == "y" ]]; then
  npx wrangler d1 execute keyword-tracker-db --file migrations/00_drop_tables.sql
  npx wrangler d1 execute keyword-tracker-db --file migrations/01_create_accounts.sql
  npx wrangler d1 execute keyword-tracker-db --file migrations/02_create_nodes.sql
else
   exit 0
fi